/*
 * test_control_reply.c — Phase 6 6-5/M4b host test for control_reply.c (pure logic).
 *
 * WHAT IT PINS: the v2 JRPL reply wire format by RAW OFFSET, the CRC region, the HMAC span
 * (which deliberately COVERS the CRC), the printable-sanitize, the clamp/guard behaviour, and
 * a GOLDEN 97-byte payload for the shared cross-language vector.
 *
 * THE GOLDEN IS THE CROSS-LANGUAGE COUPLING. The same vector is decoded by the receiver's
 * Python reply decoder (phase3/scripts/telemetry_receiver.py, pinned in
 * test_telemetry_receiver.py). It was generated by an INDEPENDENT implementation — Python's
 * stdlib zlib.crc32 + hmac/hashlib — so this test passing means the C builder agrees with the
 * language the receiver is written in, not merely with itself:
 *
 *     key     = bytes(range(1, 33))          -> 0x01..0x20 (the box JKEY test slot)
 *     verdict = 0 (answered)
 *     seq     = 4242
 *     text    = "a page fault is a memory access to an unmapped page"   (51 B, all printable)
 *     => tlen = 51, total = 46 + 51 = 97
 *
 * Change one side => change both, and re-run both suites.
 *
 * Build/run:
 *   gcc -Wall -Werror -O2 -std=c11 -I phase3/src/net -I phase3/src/crypto \
 *       phase3/src/net/test_control_reply.c phase3/src/net/control_reply.c \
 *       phase3/src/crypto/hmac_sha256.c phase3/src/crypto/sha256.c -o /tmp/t_reply && /tmp/t_reply
 */
#include "control_reply.h"
#include "hmac_sha256.h"
#include <stdio.h>
#include <string.h>
#include <stdint.h>

static int pass = 0, fail = 0;
#define CHECK(c, msg) do { \
    if (c) { pass++; } \
    else   { fail++; printf("  FAIL: %s (line %d)\n", msg, __LINE__); } \
} while (0)

/* The fixed TEST key (the real box key lives in the NVMe JKEY slot). Identical to the key in
 * test_control_signer_differential.c — both directions share ONE symmetric key. */
static const uint8_t KEY[32] = {
    0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,
    0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,0x10,
    0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,
    0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,0x20
};

#define GOLDEN_SEQ     4242u
#define GOLDEN_VERDICT 0u
static const char GOLDEN_TEXT[] = "a page fault is a memory access to an unmapped page";
#define GOLDEN_TLEN  51u
#define GOLDEN_TOTAL 97u

/* VERBATIM output of the independent Python generator for the vector above. */
static const uint8_t GOLDEN[GOLDEN_TOTAL] = {
    0x4A, 0x52, 0x50, 0x4C, 0x02, 0x00, 0x92, 0x10,
    0x33, 0x00, 0x61, 0x20, 0x70, 0x61, 0x67, 0x65,
    0x20, 0x66, 0x61, 0x75, 0x6C, 0x74, 0x20, 0x69,
    0x73, 0x20, 0x61, 0x20, 0x6D, 0x65, 0x6D, 0x6F,
    0x72, 0x79, 0x20, 0x61, 0x63, 0x63, 0x65, 0x73,
    0x73, 0x20, 0x74, 0x6F, 0x20, 0x61, 0x6E, 0x20,
    0x75, 0x6E, 0x6D, 0x61, 0x70, 0x70, 0x65, 0x64,
    0x20, 0x70, 0x61, 0x67, 0x65, 0x73, 0x80, 0x19,
    0x7F, 0x09, 0x09, 0x57, 0x44, 0x5F, 0x3C, 0xEA,
    0x5A, 0xB6, 0x8F, 0xA2, 0xF8, 0xF9, 0x93, 0x12,
    0xD4, 0x44, 0x44, 0x67, 0xBE, 0x44, 0x73, 0xDF,
    0xA4, 0x1B, 0xAF, 0x6C, 0x5C, 0x8B, 0x42, 0xB7,
    0xEE
};

/* Little-endian scalar readers — assert the ON-WIRE byte order explicitly rather than
 * trusting any host struct layout. */
static uint32_t rd_le32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}
static uint16_t rd_le16(const uint8_t *p) {
    return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}
/* the magic is the ONE big-endian-read field (its bytes sit on the wire in order) */
static uint32_t rd_be32(const uint8_t *p) {
    return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) | ((uint32_t)p[2] << 8) | (uint32_t)p[3];
}

int main(void)
{
    printf("== test_control_reply ==\n");

    /* ---- T1: RAW OFFSETS — every field lands where the wire format says ---- */
    {
        uint8_t out[CTRL_REPLY_MAX_LEN];
        const char *txt = "hello";
        int n = ctrl_build_reply(KEY, 1, 0xBEEF, (const uint8_t *)txt, 5, out, sizeof out);
        CHECK(n == (int)(CTRL_REPLY_OVERHEAD + 5u), "total == 46 + tlen (51 for tlen=5)");
        CHECK(n == 51, "total == 51 explicitly");
        CHECK(memcmp(out, "JRPL", 4) == 0,        "raw: magic @0 == 'JRPL'");
        /* the magic bytes are in-order on the wire => the scalar is their BE reading
         * (the control_msg.h CONTROL_MAGIC convention); everything ELSE is little-endian. */
        CHECK(rd_be32(out) == CTRL_REPLY_MAGIC,   "raw: magic BE @0 == CTRL_REPLY_MAGIC");
        CHECK(out[0] == 0x4A && out[1] == 0x52 && out[2] == 0x50 && out[3] == 0x4C,
              "raw: magic bytes are 4A 52 50 4C IN ORDER (what the receiver matches)");
        CHECK(out[4] == 2,                        "raw: version @4 == 2 (v2 = HMAC'd)");
        CHECK(out[4] == (uint8_t)CTRL_REPLY_VERSION, "raw: version @4 == CTRL_REPLY_VERSION");
        CHECK(out[5] == 1,                        "raw: verdict @5");
        CHECK(rd_le16(&out[6]) == 0xBEEF,         "raw: seq u16 LE @6");
        CHECK(out[6] == 0xEF && out[7] == 0xBE,   "raw: seq bytes are LITTLE-ENDIAN (EF BE)");
        CHECK(rd_le16(&out[8]) == 5,              "raw: tlen u16 LE @8");
        CHECK(memcmp(&out[10], txt, 5) == 0,      "raw: text @10");
        CHECK(rd_le32(&out[10 + 5]) == ctrl_reply_crc32(out, 10 + 5),
              "raw: crc u32 LE @10+tlen covers exactly [0,10+tlen)");
        /* tag @14+tlen — independently recomputed below in T2 */
        CHECK(CTRL_REPLY_HDR_LEN == 10u && CTRL_REPLY_CRC_LEN == 4u && CTRL_REPLY_TAG_LEN == 32u,
              "constants: hdr 10 / crc 4 / tag 32");
        CHECK(CTRL_REPLY_OVERHEAD == 46u, "constants: fixed overhead == 46");
        CHECK(CTRL_REPLY_MAX_LEN == 558u, "constants: max payload == 10+512+4+32 == 558");
    }

    /* ---- T2: the tag is a REAL HMAC over [0, 14+tlen) — recomputed independently ---- */
    {
        uint8_t out[CTRL_REPLY_MAX_LEN];
        const char *txt = "verify me";
        uint32_t tl = 9;
        int n = ctrl_build_reply(KEY, 0, 7, (const uint8_t *)txt, tl, out, sizeof out);
        CHECK(n == (int)(CTRL_REPLY_OVERHEAD + tl), "T2 build ok");

        uint32_t tag_off = CTRL_REPLY_HDR_LEN + tl + CTRL_REPLY_CRC_LEN;   /* 14 + tlen */
        CHECK(tag_off == 14u + tl, "T2 tag offset == 14 + tlen");

        uint8_t expect[32];
        hmac_sha256(KEY, 32, out, (size_t)tag_off, expect);   /* recompute, do not trust the builder */
        CHECK(memcmp(out + tag_off, expect, 32) == 0,
              "T2 tag == independently recomputed hmac_sha256(key, payload[0:14+tlen])");
        CHECK(hmac_sha256_verify(KEY, 32, out, (size_t)tag_off, out + tag_off) == 1,
              "T2 tag passes the constant-time verifier (what the receiver runs)");

        /* KEY-BOUND, not a structural fluke: one bit different in the key must fail. */
        uint8_t wrong[32]; memcpy(wrong, KEY, 32); wrong[0] ^= 0x01;
        CHECK(hmac_sha256_verify(wrong, 32, out, (size_t)tag_off, out + tag_off) == 0,
              "T2 one-bit-different key -> verify FAILS (the tag is key-bound)");
    }

    /* ---- T3: the CRC is the standard zlib/IEEE CRC-32 (the interop-defining property) ---- */
    {
        CHECK(ctrl_reply_crc32((const uint8_t *)"123456789", 9) == 0xCBF43926u,
              "T3 canonical vector crc32(\"123456789\") == 0xCBF43926 (== Python zlib.crc32)");
        CHECK(ctrl_reply_crc32((const uint8_t *)"", 0) == 0u, "T3 crc32(empty) == 0");

        uint8_t out[CTRL_REPLY_MAX_LEN];
        uint32_t tl = 12;
        int n = ctrl_build_reply(KEY, 2, 1, (const uint8_t *)"crc coverage", tl, out, sizeof out);
        CHECK(n > 0, "T3 build ok");
        uint32_t crc_off = CTRL_REPLY_HDR_LEN + tl;
        CHECK(rd_le32(out + crc_off) == ctrl_reply_crc32(out, crc_off),
              "T3 stored crc == recomputation over [0, 10+tlen)");
        /* The CRC does NOT cover itself or the tag — pin that boundary explicitly. */
        CHECK(ctrl_reply_crc32(out, crc_off) != ctrl_reply_crc32(out, crc_off + 4u),
              "T3 crc region boundary is [0,10+tlen), NOT including the crc field");
    }

    /* ---- T4: TAMPER TEETH — the tag covers header, text AND the crc bytes ---- */
    {
        uint32_t tl = 20;
        const char *txt = "twenty bytes of text";
        struct { uint32_t off; const char *what; } spots[] = {
            {  5u, "header/verdict" },
            {  6u, "header/seq"     },
            { 10u, "text[0]"        },
            { 29u, "text[last]"     },
            { 30u, "crc byte 0"     },   /* 10 + tlen */
            { 33u, "crc byte 3"     },
        };
        for (unsigned i = 0; i < sizeof spots / sizeof spots[0]; i++) {
            uint8_t out[CTRL_REPLY_MAX_LEN];
            int n = ctrl_build_reply(KEY, 0, 99, (const uint8_t *)txt, tl, out, sizeof out);
            CHECK(n == (int)(CTRL_REPLY_OVERHEAD + tl), "T4 pre-tamper build ok");

            uint32_t tag_off = CTRL_REPLY_HDR_LEN + tl + CTRL_REPLY_CRC_LEN;   /* 34 */
            CHECK(hmac_sha256_verify(KEY, 32, out, (size_t)tag_off, out + tag_off) == 1,
                  "T4 pre-tamper tag verifies");

            out[spots[i].off] ^= 0x01;   /* flip one bit, leave the tag alone */
            if (hmac_sha256_verify(KEY, 32, out, (size_t)tag_off, out + tag_off) != 0) {
                fail++; printf("  FAIL: tamper in %s NOT caught by the tag (line %d)\n",
                               spots[i].what, __LINE__);
            } else { pass++; }
        }
        /* The whole point of signing over the CRC: an attacker who edits text AND fixes up the
         * CRC (so crc_ok would pass) still cannot produce a valid tag without the key. */
        uint8_t out[CTRL_REPLY_MAX_LEN];
        int n = ctrl_build_reply(KEY, 0, 99, (const uint8_t *)txt, tl, out, sizeof out);
        CHECK(n > 0, "T4 build for the crc-relaunder case");
        uint32_t crc_off = CTRL_REPLY_HDR_LEN + tl, tag_off = crc_off + 4u;
        out[12] ^= 0x20;                                   /* edit the text */
        uint32_t fixed = ctrl_reply_crc32(out, crc_off);   /* attacker recomputes the CRC */
        out[crc_off + 0] = (uint8_t)(fixed);        out[crc_off + 1] = (uint8_t)(fixed >> 8);
        out[crc_off + 2] = (uint8_t)(fixed >> 16);  out[crc_off + 3] = (uint8_t)(fixed >> 24);
        CHECK(rd_le32(out + crc_off) == ctrl_reply_crc32(out, crc_off),
              "T4 relaundered frame would PASS a crc-only check");
        CHECK(hmac_sha256_verify(KEY, 32, out, (size_t)tag_off, out + tag_off) == 0,
              "T4 ...but FAILS the tag — this is exactly the hole M4b closes");
    }

    /* ---- T5: THE GOLDEN — full 97-byte byte-match against the Python-generated vector ---- */
    {
        uint8_t out[CTRL_REPLY_MAX_LEN];
        memset(out, 0xAA, sizeof out);
        int n = ctrl_build_reply(KEY, (uint8_t)GOLDEN_VERDICT, (uint16_t)GOLDEN_SEQ,
                                 (const uint8_t *)GOLDEN_TEXT, GOLDEN_TLEN, out, sizeof out);
        CHECK(n == (int)GOLDEN_TOTAL, "T5 golden total == 97 (46 + 51)");
        CHECK(strlen(GOLDEN_TEXT) == GOLDEN_TLEN, "T5 golden text is 51 bytes");
        if (memcmp(out, GOLDEN, GOLDEN_TOTAL) == 0) { pass++; }
        else {
            fail++;
            printf("  FAIL: GOLDEN byte mismatch (line %d)\n  got: ", __LINE__);
            for (unsigned i = 0; i < GOLDEN_TOTAL; i++) printf("%02x", out[i]);
            printf("\n  exp: ");
            for (unsigned i = 0; i < GOLDEN_TOTAL; i++) printf("%02x", GOLDEN[i]);
            printf("\n");
        }
        /* the golden's own internals, so a mismatch localizes */
        CHECK(GOLDEN[4] == 2, "T5 golden version byte == 2");
        CHECK(rd_le16(&GOLDEN[6]) == GOLDEN_SEQ, "T5 golden seq == 4242");
        CHECK(rd_le16(&GOLDEN[8]) == GOLDEN_TLEN, "T5 golden tlen == 51");
        CHECK(rd_le32(&GOLDEN[10 + GOLDEN_TLEN]) == ctrl_reply_crc32(GOLDEN, 10 + GOLDEN_TLEN),
              "T5 golden crc validates under the C crc32 (Python zlib parity)");
        CHECK(hmac_sha256_verify(KEY, 32, GOLDEN, 14 + GOLDEN_TLEN,
                                 GOLDEN + 14 + GOLDEN_TLEN) == 1,
              "T5 golden tag validates under the C HMAC (Python hmac parity)");
    }

    /* ---- T6: out_cap guard — negative return, buffer NOT partially written ---- */
    {
        uint8_t out[CTRL_REPLY_MAX_LEN];
        memset(out, 0xAA, sizeof out);
        /* tlen 10 needs 56; give it 55. */
        int n = ctrl_build_reply(KEY, 0, 1, (const uint8_t *)"0123456789", 10, out, 55);
        CHECK(n < 0, "T6 out_cap one byte short -> negative");
        int untouched = 1;
        for (unsigned i = 0; i < sizeof out; i++) if (out[i] != 0xAA) untouched = 0;
        CHECK(untouched == 1, "T6 rejected build wrote NOTHING (no partial payload)");

        /* exactly enough succeeds — the boundary is inclusive */
        memset(out, 0xAA, sizeof out);
        n = ctrl_build_reply(KEY, 0, 1, (const uint8_t *)"0123456789", 10, out, 56);
        CHECK(n == 56, "T6 out_cap exactly 56 -> builds (boundary inclusive)");
        CHECK(out[56] == 0xAA, "T6 build wrote nothing PAST the returned length");

        /* cap 0 on an empty text still needs 46 */
        n = ctrl_build_reply(KEY, 0, 1, NULL, 0, out, 0);
        CHECK(n < 0, "T6 out_cap 0 -> negative even for empty text");
    }

    /* ---- T7: clamp — text_len > 512 becomes exactly 512 ---- */
    {
        static uint8_t big[2000];
        memset(big, 'x', sizeof big);
        uint8_t out[CTRL_REPLY_MAX_LEN];
        int n = ctrl_build_reply(KEY, 0, 5, big, sizeof big, out, sizeof out);
        CHECK(n == (int)CTRL_REPLY_MAX_LEN, "T7 over-long text clamps to the max payload (558)");
        CHECK(n == (int)(CTRL_REPLY_OVERHEAD + CTRL_REPLY_TEXT_MAX), "T7 total == 46 + 512");
        CHECK(rd_le16(&out[8]) == CTRL_REPLY_TEXT_MAX, "T7 tlen field == 512 (clamped, not errored)");
        CHECK(out[10] == 'x' && out[10 + 511] == 'x', "T7 clamped text is the first 512 bytes");
        uint32_t tag_off = CTRL_REPLY_HDR_LEN + CTRL_REPLY_TEXT_MAX + 4u;
        CHECK(hmac_sha256_verify(KEY, 32, out, (size_t)tag_off, out + tag_off) == 1,
              "T7 clamped max-size reply still signs correctly");

        /* exactly 512 is NOT clamped-away */
        n = ctrl_build_reply(KEY, 0, 5, big, CTRL_REPLY_TEXT_MAX, out, sizeof out);
        CHECK(n == (int)CTRL_REPLY_MAX_LEN, "T7 text_len exactly 512 -> full payload");
    }

    /* ---- T8: PRINTABLE-SANITIZE happens in the builder (the caller can forget) ---- */
    {
        uint8_t raw[8] = { 0x00, 0x09, 0x0A, 0x1F, 'A', 0x7F, 0x80, 0xFF };
        uint8_t out[CTRL_REPLY_MAX_LEN];
        int n = ctrl_build_reply(KEY, 0, 1, raw, 8, out, sizeof out);
        CHECK(n == (int)(CTRL_REPLY_OVERHEAD + 8u), "T8 build ok");
        CHECK(out[10] == '.' && out[11] == '.' && out[12] == '.' && out[13] == '.',
              "T8 control bytes (00/09/0A/1F) -> '.'");
        CHECK(out[14] == 'A', "T8 printable 'A' survives");
        CHECK(out[15] == '.' && out[16] == '.' && out[17] == '.',
              "T8 0x7F/0x80/0xFF -> '.' (0x7f is EXCLUSIVE)");
        /* boundaries: 0x20 (space) in, 0x7e (~) in */
        uint8_t edge[2] = { 0x20, 0x7E };
        n = ctrl_build_reply(KEY, 0, 1, edge, 2, out, sizeof out);
        CHECK(n > 0 && out[10] == 0x20 && out[11] == 0x7E,
              "T8 boundary bytes 0x20 and 0x7E are printable and survive");
        /* an embedded NUL does NOT truncate — tlen is length-carried, never strlen */
        uint8_t emb[5] = { 'a', 0x00, 'b', 0x00, 'c' };
        n = ctrl_build_reply(KEY, 0, 1, emb, 5, out, sizeof out);
        CHECK(n == (int)(CTRL_REPLY_OVERHEAD + 5u) && rd_le16(&out[8]) == 5,
              "T8 embedded NUL does not truncate (length-carried)");
        CHECK(out[10] == 'a' && out[11] == '.' && out[12] == 'b' && out[13] == '.' && out[14] == 'c',
              "T8 embedded NULs sanitize to '.' in place");
    }

    /* ---- T9: NULL / empty guards ---- */
    {
        uint8_t out[CTRL_REPLY_MAX_LEN];
        CHECK(ctrl_build_reply(NULL, 0, 1, (const uint8_t *)"x", 1, out, sizeof out) < 0,
              "T9 NULL key -> negative (never sign with nothing)");
        CHECK(ctrl_build_reply(KEY, 0, 1, (const uint8_t *)"x", 1, NULL, 100) < 0,
              "T9 NULL out -> negative");

        /* tlen == 0 is a valid reply (total 46) */
        int n = ctrl_build_reply(KEY, 2, 77, NULL, 0, out, sizeof out);
        CHECK(n == (int)CTRL_REPLY_OVERHEAD, "T9 tlen 0 -> total 46");
        CHECK(rd_le16(&out[8]) == 0, "T9 tlen field 0");
        CHECK(rd_le32(&out[10]) == ctrl_reply_crc32(out, 10), "T9 tlen 0: crc @10 over the header");
        CHECK(hmac_sha256_verify(KEY, 32, out, 14, out + 14) == 1, "T9 tlen 0: tag @14 verifies");

        /* NULL text with tlen > 0 is SAFE (documented): emits '.' rather than dereferencing */
        n = ctrl_build_reply(KEY, 0, 1, NULL, 4, out, sizeof out);
        CHECK(n == (int)(CTRL_REPLY_OVERHEAD + 4u), "T9 NULL text + tlen 4 -> builds (no crash)");
        CHECK(out[10] == '.' && out[11] == '.' && out[12] == '.' && out[13] == '.',
              "T9 NULL text emits '.' bytes (documented, safe)");
    }

    /* ---- T10: distinct inputs produce distinct signed payloads (no constant tag) ---- */
    {
        uint8_t a[CTRL_REPLY_MAX_LEN], b[CTRL_REPLY_MAX_LEN];
        int na = ctrl_build_reply(KEY, 0, 1, (const uint8_t *)"same", 4, a, sizeof a);
        int nb = ctrl_build_reply(KEY, 1, 1, (const uint8_t *)"same", 4, b, sizeof b);
        CHECK(na == nb && na > 0, "T10 same length");
        CHECK(memcmp(a, b, (size_t)na) != 0, "T10 a different verdict changes the payload");
        CHECK(memcmp(a + 14 + 4, b + 14 + 4, 32) != 0, "T10 ...and the TAG (verdict is authenticated)");

        int nc = ctrl_build_reply(KEY, 0, 2, (const uint8_t *)"same", 4, b, sizeof b);
        CHECK(nc == na && memcmp(a + 14 + 4, b + 14 + 4, 32) != 0,
              "T10 a different seq changes the TAG (seq is authenticated -> no reply re-pointing)");

        /* deterministic: same inputs, same bytes */
        int nd = ctrl_build_reply(KEY, 0, 1, (const uint8_t *)"same", 4, b, sizeof b);
        CHECK(nd == na && memcmp(a, b, (size_t)na) == 0, "T10 build is deterministic");
    }

    printf("== %d PASS, %d FAIL ==\n", pass, fail);
    return fail ? 1 : 0;
}
