/*
 * JARVIS AI-OS - BCM2711 Hardware RNG Driver
 *
 * Week 47: iproc-rng200 hardware random number generator.
 * RNG registers at paddr 0xFE104000, mapped via uart_device_map_page().
 *
 * Must be initialized AFTER watchdog (0xFE100000) and BEFORE UART
 * (0xFE200000+) in the boot sequence due to seL4 forward-only
 * device untyped watermark.
 *
 * Reference: Linux drivers/char/hw_random/iproc-rng200.c
 */

#ifndef BCM_RNG_H
#define BCM_RNG_H

#include <stdint.h>
#include <stdbool.h>

/* ================================================================
 * iproc-rng200 Physical Address
 * ================================================================ */
#define RNG_BASE_PADDR      0xFE104000u

/* ================================================================
 * Register Offsets
 * ================================================================ */
#define RNG_CTRL            0x00
#define RNG_SOFT_RESET      0x04
#define RBG_SOFT_RESET      0x08
#define RNG_TOTAL_BIT_CNT   0x0C
#define RNG_TOTAL_BIT_CNT_THRESHOLD  0x10
#define RNG_INT_STATUS      0x18
#define RNG_INT_ENABLE      0x1C
#define RNG_FIFO_DATA       0x20
#define RNG_FIFO_COUNT      0x24

/* ================================================================
 * Control Bits
 * ================================================================ */
#define RNG_CTRL_RBG_EN     (1u << 1)   /* Enable RBG (raw entropy) */
#define RNG_CTRL_RBGEN      (1u << 0)   /* Enable DRBG (not used) */

/* FIFO count: bits 7:0 = number of 32-bit words available */
#define RNG_FIFO_COUNT_MASK 0xFFu

/* ================================================================
 * Error Codes
 * ================================================================ */
#define RNG_OK              0
#define RNG_ERR_NOT_INIT    (-1)
#define RNG_ERR_TIMEOUT     (-2)

/* Timeout for waiting for entropy (microseconds) */
#define RNG_TIMEOUT_US      100000

/* ================================================================
 * Public API
 * ================================================================ */

/*
 * Initialize RNG driver.
 * Maps iproc-rng200 register page at 0xFE104000 via uart_device_map_page().
 * Must be called AFTER watchdog_init() and BEFORE uart_init().
 * Returns 0 on success, -1 on failure.
 */
int rng_init(void);

/*
 * Read hardware entropy into buffer.
 * Fills buf with len bytes of random data from the hardware FIFO.
 * Returns 0 on success, RNG_ERR_TIMEOUT if FIFO does not fill in time.
 */
int rng_read(void *buf, uint32_t len);

/*
 * Read a single 32-bit random word.
 * Blocks until FIFO has at least one word available.
 * Returns the random value (0 if not initialized).
 */
uint32_t rng_read_word(void);

/*
 * Return current FIFO word count (0-255).
 */
uint32_t rng_fifo_count(void);

/*
 * Return total number of bits generated by hardware.
 */
uint64_t rng_total_bits(void);

/*
 * Check if RNG driver is initialized.
 */
bool rng_is_initialized(void);

/*
 * Get RNG status string for shell commands.
 * Writes formatted status into output buffer.
 * Returns bytes written (excluding NUL).
 */
int rng_get_status(char *output, uint32_t output_size);

#endif /* BCM_RNG_H */
