#!/usr/bin/env python3
"""
gen_control_vectors.py  (Phase 6 goal 6-5 control-IN differential-fuzz support)

One-shot, committed-for-reproducibility generator that emits two self-contained,
include-guarded C headers used by the differential crypto fuzz:

  phase3/src/crypto/sha256_vectors.h  - the 3 canonical NIST SHA-256 test vectors
                                        (empty string, "abc", the 56-byte
                                        two-block message) as {msg bytes+len, exp[32]}
  phase3/src/crypto/hmac_vectors.h    - N=1000 random (key, msg, tag) HMAC-SHA256
                                        triples computed with Python's stdlib
                                        hashlib/hmac (the INDEPENDENT reference),
                                        varied key lengths (1..80) and msg lengths
                                        (0..200), fixed seed for reproducibility.

Both headers embed all data as static const arrays so a C fuzz can loop them with
NO Python at test time.

Run:
  python3 phase3/scripts/gen_control_vectors.py
"""

import argparse
import hashlib
import hmac
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT_DIR = os.path.join(REPO, "phase3", "src", "crypto")

# --- HMAC vector parameters --------------------------------------------------
N_HMAC = 1000
SEED = 0x6C6F6E67  # fixed => reproducible bytes across runs
KEY_MIN, KEY_MAX = 1, 80
MSG_MIN, MSG_MAX = 0, 200


def c_byte_array(data):
    """Render a bytes object as a comma-separated list of 0xNN literals."""
    if len(data) == 0:
        return "0x00"  # keep a valid (unused) element for zero-length arrays
    return ", ".join("0x%02x" % b for b in data)


def gen_sha256_header():
    # The 3 canonical NIST FIPS-180 SHA-256 vectors.
    vectors = [
        (b"", "empty string"),
        (b"abc", "abc"),
        (b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
         "56-byte two-block message"),
    ]
    lines = []
    lines.append("/* AUTO-GENERATED by phase3/scripts/gen_control_vectors.py - DO NOT EDIT. */")
    lines.append("/* Canonical NIST FIPS-180 SHA-256 test vectors. */")
    lines.append("#ifndef JARVIS_SHA256_VECTORS_H")
    lines.append("#define JARVIS_SHA256_VECTORS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    max_msg = max((len(m) for m, _ in vectors), default=1)
    if max_msg == 0:
        max_msg = 1

    lines.append("typedef struct {")
    lines.append("    const char *name;")
    lines.append("    uint8_t     msg[%d];" % max_msg)
    lines.append("    int         mlen;")
    lines.append("    uint8_t     exp[32];")
    lines.append("} sha256_vector_t;")
    lines.append("")
    lines.append("static const sha256_vector_t SHA256_VECTORS[] = {")
    for msg, name in vectors:
        exp = hashlib.sha256(msg).digest()
        lines.append("    {")
        lines.append('        "%s",' % name)
        lines.append("        { %s }," % c_byte_array(msg))
        lines.append("        %d," % len(msg))
        lines.append("        { %s }," % c_byte_array(exp))
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("#define SHA256_VECTOR_COUNT "
                 "((int)(sizeof(SHA256_VECTORS) / sizeof(SHA256_VECTORS[0])))")
    lines.append("")
    lines.append("#endif /* JARVIS_SHA256_VECTORS_H */")
    lines.append("")

    return "\n".join(lines)


def gen_hmac_header():
    rng = random.Random(SEED)

    triples = []
    max_key = 1
    max_msg = 1
    for _ in range(N_HMAC):
        klen = rng.randint(KEY_MIN, KEY_MAX)
        mlen = rng.randint(MSG_MIN, MSG_MAX)
        key = bytes(rng.randint(0, 255) for _ in range(klen))
        msg = bytes(rng.randint(0, 255) for _ in range(mlen))
        tag = hmac.new(key, msg, hashlib.sha256).digest()
        triples.append((key, msg, tag))
        if klen > max_key:
            max_key = klen
        if mlen > max_msg:
            max_msg = mlen

    lines = []
    lines.append("/* AUTO-GENERATED by phase3/scripts/gen_control_vectors.py - DO NOT EDIT. */")
    lines.append("/* %d random HMAC-SHA256 (key,msg,tag) triples computed with Python's" % N_HMAC)
    lines.append("   stdlib hashlib/hmac (the independent reference). Seed=0x%08x. */" % SEED)
    lines.append("#ifndef JARVIS_HMAC_VECTORS_H")
    lines.append("#define JARVIS_HMAC_VECTORS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    uint8_t key[%d];" % max_key)
    lines.append("    int     klen;")
    lines.append("    uint8_t msg[%d];" % max_msg)
    lines.append("    int     mlen;")
    lines.append("    uint8_t tag[32];")
    lines.append("} hmac_vector_t;")
    lines.append("")
    lines.append("static const hmac_vector_t HMAC_VECTORS[] = {")
    for key, msg, tag in triples:
        lines.append("    { { %s }, %d, { %s }, %d, { %s } },"
                     % (c_byte_array(key), len(key),
                        c_byte_array(msg), len(msg),
                        c_byte_array(tag)))
    lines.append("};")
    lines.append("")
    lines.append("#define HMAC_VECTOR_COUNT "
                 "((int)(sizeof(HMAC_VECTORS) / sizeof(HMAC_VECTORS[0])))")
    lines.append("")
    lines.append("#endif /* JARVIS_HMAC_VECTORS_H */")
    lines.append("")

    return "\n".join(lines)


def _check_one(path, text):
    """True if the committed file matches regeneration.

    Compares CONTENT, not line endings (the gen_embed_mu.py --check precedent): a
    checkout under autocrlf=true would otherwise fail on every line.
    """
    name = os.path.basename(path)
    if not os.path.exists(path):
        print("FAIL: %s does not exist - run without --check to generate it" % name)
        return False
    with open(path, "r", newline="") as f:
        on_disk = f.read()
    if on_disk.replace("\r\n", "\n") != text.replace("\r\n", "\n"):
        print("FAIL: %s is STALE - regenerate with gen_control_vectors.py" % name)
        print("      on disk %d chars, regenerated %d chars" % (len(on_disk), len(text)))
        return False
    print("OK: %s matches regeneration (%d chars)" % (name, len(on_disk)))
    return True


def main():
    ap = argparse.ArgumentParser(
        description="Generate (or verify) the committed SHA-256 / HMAC test vectors.")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed headers match regeneration; write nothing")
    args = ap.parse_args()

    sha_path = os.path.join(OUT_DIR, "sha256_vectors.h")
    hmac_path = os.path.join(OUT_DIR, "hmac_vectors.h")
    sha_text = gen_sha256_header()
    hmac_text = gen_hmac_header()

    if args.check:
        # DRIFT GATE. These headers are fuzz_control_in.c's differential oracle: it
        # checks our C SHA-256/HMAC against vectors Python computed. If the committed
        # headers stop matching what the generator produces, the fuzzer is still green
        # while attesting something nobody generated -- a weakened oracle with no red
        # light. Generation is deterministic (fixed SEED, no time, no urandom), so a
        # mismatch is real drift, never flake.
        ok = _check_one(sha_path, sha_text) & _check_one(hmac_path, hmac_text)
        return 0 if ok else 1

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(sha_path, "w", newline="\n") as f:
        f.write(sha_text)
    with open(hmac_path, "w", newline="\n") as f:
        f.write(hmac_text)
    print("wrote %s (%d lines, 3 vectors)" % (sha_path, sha_text.count("\n")))
    print("wrote %s (%d lines, %d vectors)" % (hmac_path, hmac_text.count("\n"), N_HMAC))
    return 0


if __name__ == "__main__":
    # sys.exit(main()) -- NOT a bare main(): --check signals drift through the exit
    # code, and discarding it would make the CI gate incapable of ever failing.
    sys.exit(main())
