#!/usr/bin/env python3
"""C -> Python round-trip for the JVEC vector store parser.

The fixture is written by test_embed_store.c --dump THROUGH THE REAL embed_store.c
(the nvme_log / episodic --dump precedent), so this asserts against bytes that
module actually produced. A layout change breaks this step rather than the next
forensic read of the box.

Run:  python3 phase3/scripts/test_parse_embed_store.py <fixture.bin>
"""
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from parse_embed_store import (  # noqa: E402
    parse_header, iter_records, parse_record,
    EMBED_STORE_MAGIC, EMBED_HDR_SIZE, EMBED_REC_SIZE, EMBED_DIM,
)

_PASS = 0
_FAIL = 0


def check(cond, msg):
    global _PASS, _FAIL
    if cond:
        _PASS += 1
        print('  PASS: %s' % msg)
    else:
        _FAIL += 1
        print('  FAIL: %s' % msg)


def nr_sqrt(v):
    """Byte-for-byte the C nr_sqrt() in test_embed_store.c.

    FIXED 40 iterations, never convergence-tested: NR for sqrt can oscillate
    between two adjacent doubles at the fixed point, so "stop when it stops
    changing" is not reproducible across implementations. Python floats are IEEE
    doubles and +, * and / have identical semantics to C double, so the same
    recurrence lands on the same bits — which is what lets the vector comparison
    below be a BYTE comparison rather than a tolerance.
    """
    if v <= 0.0:
        return 0.0
    x = v if v > 1.0 else 1.0
    for _ in range(40):
        x = 0.5 * (x + v / x)
    return x


def expected_vec_bytes(i):
    """Regenerate record i's vector exactly as dump_fixture() does, and return it
    as the 512 raw bytes the store would hold."""
    raw = [(float(((d + i) % 7) - 3)) / 8.0 for d in range(EMBED_DIM)]
    ss = 0.0
    for r in raw:
        ss += r * r
    norm = nr_sqrt(ss)
    # ONE rounding double -> float32, matching the single C cast.
    return struct.pack('<%df' % EMBED_DIM, *[r / norm for r in raw])


def main(argv):
    if len(argv) != 1:
        print('usage: test_parse_embed_store.py <fixture.bin>', file=sys.stderr)
        return 2
    with open(argv[0], 'rb') as fh:
        data = fh.read()

    print('=== JVEC parser round-trip (fixture: %s, %d bytes) ===' % (argv[0], len(data)))

    # ---- header ----
    hdr = parse_header(data)
    check(hdr['magic'] == EMBED_STORE_MAGIC, 'header magic is EMBED_STORE_MAGIC (0x4A564543)')
    check(hdr['magic_bytes_on_disk'] == 'CEVJ',
          "on-disk magic bytes are 'CEVJ' -- the LE spelling; a dump is NOT prefixed 'JVEC'")
    check(hdr['version'] == 1, 'header version == 1')
    check(hdr['dim'] == EMBED_DIM, 'header dim == 128')
    check(hdr['total_entries'] == 6, 'header total_entries == 6 (got %d)' % hdr['total_entries'])
    check(hdr['cursor'] == 6, 'header cursor == 6 (got %d)' % hdr['cursor'])
    check(hdr['checksum_ok'], 'header XOR checksum verifies')
    check(hdr['boot_id'] == 1, 'header boot_id == 1 (fresh init)')

    # ---- records ----
    recs = [r for _, r in iter_records(data)]
    check(len(recs) == 6, 'six records decoded (got %d)' % len(recs))

    for i, r in enumerate(recs):
        check(r['owner_seq'] == 10 * i + 1,
              'record %d owner_seq == %d' % (i, 10 * i + 1))
        check(r['owner_key'] == 0x1122334455667700 + i,
              'record %d owner_key == 0x%016x' % (i, 0x1122334455667700 + i))
        check(r['dim'] == EMBED_DIM, 'record %d dim == 128' % i)
        check(r['status'] == 1, 'record %d status == VALID' % i)
        check(r['checksum_ok'], 'record %d per-record XOR checksum verifies' % i)
        check(r['seq'] == i, 'record %d store seq == %d (append order)' % (i, i))
        check(abs(r['l2_norm'] - 1.0) < 1e-6,
              'record %d |v| within 1e-6 of 1.0 (got %.9f)' % (i, r['l2_norm']))
        # BIT-EXACT, not a float tolerance: pack the parsed floats back to bytes and
        # compare against the regenerated bytes. A tolerance would hide exactly the
        # kind of one-ulp pipeline difference this round-trip exists to catch.
        got = struct.pack('<%df' % EMBED_DIM, *r['vec'])
        check(got == expected_vec_bytes(i),
              'record %d vector BIT-EXACT against the generator formula' % i)

    # ---- ordering ----
    check([r['owner_seq'] for r in recs] == [1, 11, 21, 31, 41, 51],
          'records are in oldest->newest order')

    # ---- NEGATIVE control: a corrupted record must be REPORTED, not silently accepted ----
    # Without this the checksum column could be hardcoded True and every check above
    # would still pass.
    victim = 3
    off = EMBED_HDR_SIZE + victim * EMBED_REC_SIZE
    corrupt = bytearray(data)
    corrupt[off + 4] ^= 0x01           # one byte inside the VECTOR half of record 3
    crecs = [r for _, r in iter_records(bytes(corrupt))]
    check(len(crecs) == 6, 'corrupted image still decodes six records')
    check(crecs[victim]['checksum_ok'] is False,
          'NEGATIVE: record %d reports checksum_ok False after a 1-byte vector flip' % victim)
    others_ok = all(crecs[j]['checksum_ok'] for j in range(6) if j != victim)
    check(others_ok, 'NEGATIVE: every OTHER record still verifies (damage is localised)')
    check(parse_header(bytes(corrupt))['checksum_ok'],
          'NEGATIVE: the header is untouched by a record-body flip')

    print('\ntest_parse_embed_store: %d PASS, %d FAIL' % (_PASS, _FAIL))
    return 1 if _FAIL else 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
